spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codeit?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Bartos1234
  jpa:
    hibernate:
      ddl-auto: create-drop