spring:
#  liquibase:
#    change-log: classpath:/db/changelog/master.xml
  datasource:
    url: jdbc:h2:mem:test
  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
    defer-datasource-initialization: true
